#ifndef UI_DIALOG_TIPS_H
#define UI_DIALOG_TIPS_H

typedef enum {
    UI_DIALOG_TIPS_NONE = 0,
    UI_DIALOG_TIPS_CONFIG_OK,
    UI_DIALOG_TIPS_CONFIG_OK_REBOOT,
    UI_DIALOG_TIPS_CONFIG_ERROR,    
    UI_DIALOG_TIPS_CONFIG_IP_OK,
    UI_DIALOG_TIPS_CONFIG_WLAN_SAVE_IP,
    UI_DIALOG_TIPS_CONNECTING,
    UI_DIALOG_TIPS_CONNECT_FAIL,
    UI_DIALOG_TIPS_CONNECT_SUCCESS,
    UI_DIALOG_TIPS_CP_BASE_INSERT_U_DISK,
    UI_DIALOG_TIPS_CP_BASE,
    UI_DIALOG_TIPS_CP_BASE_FAIL,
    UI_DIALOG_TIPS_CP_BASE_FAIL_NO_SPACE,
    UI_DIALOG_TIPS_CP_BASE_FAIL_NO_DEV,
    UI_DIALOG_TIPS_AUTH_USER_EMPTY,
    UI_DIALOG_TIPS_AUTH_PWD_EMPTY,
    UI_DIALOG_TIPS_AUTH_PWD_TOO_SHORT,
    UI_DIALOG_TIPS_AUTH_SSID_EMPTY,
    UI_DIALOG_TIPS_FORGET_NET_ENTER,
    UI_DIALOG_TIPS_OTHRE_AUTHENTICE_TYPE,
    UI_DIALOG_TIPS_AUTHENTICE_FAIL,
    UI_DIALOG_TIPS_NOT_SUPPORT_WEB_HOTSPOT,
    UI_DIALOG_TIPS_CONNECT_NOT_WHITESSID,
    UI_DIALOG_TIPS_CONNECT_TIMEOUT,
    UI_DIALOG_TIPS_SAVE_DPI,
    UI_DIALOG_TIPS_NET_AUTHING,
    UI_DIALOG_TIPS_NET_AUTH_SUCCESS,
    UI_DIALOG_TIPS_NET_AUTH_FAIL,
    UI_DIALOG_TIPS_NET_AUTH_FAIL_USER_ERR,
    UI_DIALOG_TIPS_NET_AUTH_TIMEOUT,
    UI_DIALOG_TIPS_LAYER_MANAGE,
} ui_dialog_tips_enum;

typedef enum {
    UI_DIALOG_TIPS_BG_400_140 = 0,
    UI_DIALOG_TIPS_BG_400_110,
    UI_DIALOG_TIPS_BG_400_200,
} ui_dialog_tips_bg_enum;

void ui_dialog_tips_set_timer(guint seconds);

#endif

