#ifndef UI_DIALOG_NEWDEPLOY_CONNECT_H
#define UI_DIALOG_NEWDEPLOY_CONNECT_H

typedef enum {
    UI_DIALOG_NEWDEPLOY_CONNECT_FAIL = 0,
    //UI_DIALOG_NEWDEPLOY_CONNECT_ETH,
    UI_DIALOG_NEWDEPLOY_CONNECT_CONFIG_SERVER = 1,
    UI_DIALOG_NEWDEPLOY_CONNECT_NOAUTH = 2,
    UI_DIALOG_NEWDEPLOY_CONNECT_AUTH_FAIL = 3,
} ui_dialog_newdeploy_connect_enum;


#endif

