#ifndef _UI_WIN_USER_LOGIN_H_
#define _UI_WIN_USER_LOGIN_H_


typedef enum {
    UI_WIN_USER_LOGIN_NONE = 0,
    UI_WIN_USER_LOGIN_RET_ERROR,
    UI_WIN_USER_LOGIN_RET_EUSER,
    UI_WIN_USER_LOGIN_RET_EUNKNOW,
    UI_WIN_USER_LOGIN_RET_NOIMAGE,
    UI_WIN_USER_LOGIN_RET_BIND_ERR,
    UI_WIN_USER_LOGIN_RET_OK,
    UI_WIN_USER_LOGIN_HIDE_MODPWD,
    UI_WIN_USER_LOGIN_HIDE_GUEST,
    UI_WIN_USER_LOGIN_RET_NOBIND,
    UI_WIN_USER_LOGIN_DEF_PWD_WARN,
    UI_WIN_USER_LOGIN_RET_USER_BINDED,
    UI_WIN_USER_LOGIN_RET_TIMEOUT,
    UI_WIN_AD_LOGIN_RET_DOMAIN_EXCEPTION,
    UI_WIN_AD_LOGIN_RET_USER_DISABLE,
    UI_WIN_AD_LOGIN_RET_USER_EXPIRE,
    UI_WIN_AD_LOGIN_RET_USER_NOT_AUTH_RIGHT_NOW,
    UI_WIN_LDAP_LOGIN_RET_ERROR,
} ui_win_user_login_enum;


#endif
