#ifndef UI_DIALOG_INTERACTIVE_H
#define UI_DIALOG_INTERACTIVE_H

typedef enum {
    UI_DIALOG_INTERACTIVE_NONE = 0,
    UI_DIALOG_INTERACTIVE_SHOW_AUTOSHUTDOWN,
    UI_DIALOG_INTERACTIVE_SHOW_EASYDEPLOY,
    UI_DIALOG_INTERACTIVE_SHOW_VMERR,
    UI_DIALOG_INTERACTIVE_SHOW_VMLASTERR,
    UI_DIALOG_INTERACTIVE_SHOW_DOWNLOAD_CONFIRM,
    UI_DIALOG_INTERACTIVE_SHOW_IMGBIG,
    UI_DIALOG_INTERACTIVE_SHOW_BADDRIVER,
    UI_DIALOG_INTERACTIVE_SHOW_NOTSUPPORT_XP,
    UI_DIALOG_INTERACTIVE_SHOW_NOTSUPPORT_WIN10_32,
    UI_DIALOG_INTERACTIVE_SHOW_UPGRADEERR,
    UI_DIALOG_INTERACTIVE_SHOW_IMGABNORMAL,
    UI_DIALOG_INTERACTIVE_SHOW_OSTYPERR,
    UI_DIALOG_INTERACTIVE_SHOW_OSTYPENOTSPORT,
    UI_DIALOG_INTERACTIVE_SHOW_CPUNOTSPORT,
    UI_DIALOG_INTERACTIVE_SHOW_VMMODEINILOST,
    UI_DIALOG_INTERACTIVE_SHOW_DRIVER_ERR,
    UI_DIALOG_INTERACTIVE_SHOW_CDISK_ERR,
    UI_DIALOG_INTERACTIVE_SHOW_LAYER_TEMPLETE_ERR,
    UI_DIALOG_INTERACTIVE_SHOW_INTEL_NO_AUDIO_DEVICE,
    UI_DIALOG_INTERACTIVE_SHOW_EASYDEPLOY_NOT_WIFI,
    UI_DIALOG_INTERACTIVE_SHOW_DOWNLOAD_MODE_SELECT,
    UI_DIALOG_INTERACTIVE_SHOW_NEED_MERGE,
} ui_dialog_interactive_enum;
    


#endif
