#ifndef UI_DIALOG_DOWNLOAD_H
#define UI_DIALOG_DOWNLOAD_H

typedef enum {
    UI_DIALOG_DOWNLOAD_NONE = 0,
    UI_DIALOG_DOWNLOAD_CHOICE,
    UI_DIALOG_DOWNLOAD_PROGRESS,
    UI_DIALOG_DOWNLOAD_UPDATEING,
    UI_DIALOG_DOWNLOAD_INITING,
    UI_DIALOG_USB_COPY_PROGRESS,
} ui_dialog_download_enum;


#endif
