#ifndef _UI_WIN_PASSWORD_H_
#define _UI_WIN_PASSWORD_H_


typedef enum {
    UI_WIN_PASSWD_NONE = 0,
    UI_WIN_PASSWD_RET_OK,
    UI_WIN_PASSWD_RET_ERR,
    UI_WIN_PASSWD_RET_OLDPWD_NO_CORRECT,
    UI_WIN_PASSWD_RET_NEWPWD_NO_MATCH,
    UI_WIN_PASSWD_RET_PWD_NO_CHANGE,
    UI_WIN_PASSWD_RET_PWD_HAS_SPECIAL_CHAR,
    UI_WIN_PASSWD_RET_USER_EMPTY,
    UI_WIN_PASSWD_RET_NEWPWD_EMPTY,
    UI_WIN_PASSWD_RET_OLDPWD_EMPTY,
    UI_WIN_PASSWD_RET_ERR_AD_DOMAIN,
    UI_WIN_PASSWD_RET_ERR_LDAP_USER,
    UI_WIN_PASSWD_RET_ERR_DEFAULT_PASSWD,
} ui_win_password_enum;

typedef enum {
    PASSWD_LEVEL_ERR  = -1,
    PASSWD_LEVEL_NONE = 0,
    PASSWD_LEVEL_WEAK = 1,
    PASSWD_LEVEL_MIDIUM = 2,
    PASSWD_LEVEL_STRONG = 3,
    PASSWD_LEVEL_MAX,
} ui_passwd_level;
#endif

